const COUNTRY_CODES = [
  { label: 'Andorra', shortCode: 'AD' },
  { label: 'United Arab Emirates', shortCode: 'AE' },
  { label: 'Afghanistan', shortCode: 'AF' },
  { label: 'Antigua and Barbuda', shortCode: 'AG' },
  { label: 'Anguilla', shortCode: 'AI' },
  { label: 'Albania', shortCode: 'AL' },
  { label: 'Armenia', shortCode: 'AM' },
  { label: 'Netherlands Antilles', shortCode: 'AN' },
  { label: 'Angola', shortCode: 'AO' },
  { label: 'Antarctica', shortCode: 'AQ' },
  { label: 'Argentina', shortCode: 'AR' },
  { label: 'American Samoa', shortCode: 'AS' },
  { label: 'Austria', shortCode: 'AT' },
  { label: 'Australia', shortCode: 'AU' },
  { label: 'Aruba', shortCode: 'AW' },
  { label: 'Aland Islands', shortCode: 'AX' },
  { label: 'Azerbaijan', shortCode: 'AZ' },
  { label: 'Bosnia and Herzegovina', shortCode: 'BA' },
  { label: 'Barbados', shortCode: 'BB' },
  { label: 'Bangladesh', shortCode: 'BD' },
  { label: 'Belgium', shortCode: 'BE' },
  { label: 'Burkina Faso', shortCode: 'BF' },
  { label: 'Bulgaria', shortCode: 'BG' },
  { label: 'Bahrain', shortCode: 'BH' },
  { label: 'Burundi', shortCode: 'BI' },
  { label: 'Benin', shortCode: 'BJ' },
  { label: 'Saint-Barthélemy', shortCode: 'BL' },
  { label: 'Bermuda', shortCode: 'BM' },
  { label: 'Brunei Darussalam', shortCode: 'BN' },
  { label: 'Bolivia', shortCode: 'BO' },
  { label: 'Brazil', shortCode: 'BR' },
  { label: 'Bahamas', shortCode: 'BS' },
  { label: 'Bhutan', shortCode: 'BT' },
  { label: 'Bouvet Island', shortCode: 'BV' },
  { label: 'Botswana', shortCode: 'BW' },
  { label: 'Belarus', shortCode: 'BY' },
  { label: 'Belize', shortCode: 'BZ' },
  { label: 'Canada', shortCode: 'CA' },
  { label: 'Cocos (Keeling) Islands', shortCode: 'CC' },
  { label: 'Congo, (Kinshasa)', shortCode: 'CD' },
  { label: 'Central African Republic', shortCode: 'CF' },
  { label: 'Congo (Brazzaville)', shortCode: 'CG' },
  { label: 'Switzerland', shortCode: 'CH' },
  { label: "Côte d'Ivoire", shortCode: 'CI' },
  { label: 'Cook Islands', shortCode: 'CK' },
  { label: 'Chile', shortCode: 'CL' },
  { label: 'Cameroon', shortCode: 'CM' },
  { label: 'China', shortCode: 'CN' },
  { label: 'Colombia', shortCode: 'CO' },
  { label: 'Costa Rica', shortCode: 'CR' },
  { label: 'Cuba', shortCode: 'CU' },
  { label: 'Cape Verde', shortCode: 'CV' },
  { label: 'Christmas Island', shortCode: 'CX' },
  { label: 'Cyprus', shortCode: 'CY' },
  { label: 'Czech Republic', shortCode: 'CZ' },
  { label: 'Germany', shortCode: 'DE' },
  { label: 'Djibouti', shortCode: 'DJ' },
  { label: 'Denmark', shortCode: 'DK' },
  { label: 'Dominica', shortCode: 'DM' },
  { label: 'Dominican Republic', shortCode: 'DO' },
  { label: 'Algeria', shortCode: 'DZ' },
  { label: 'Ecuador', shortCode: 'EC' },
  { label: 'Estonia', shortCode: 'EE' },
  { label: 'Egypt', shortCode: 'EG' },
  { label: 'Western Sahara', shortCode: 'EH' },
  { label: 'Eritrea', shortCode: 'ER' },
  { label: 'Spain', shortCode: 'ES' },
  { label: 'Ethiopia', shortCode: 'ET' },
  { label: 'Finland', shortCode: 'FI' },
  { label: 'Fiji', shortCode: 'FJ' },
  { label: 'Falkland Islands (Malvinas)', shortCode: 'FK' },
  { label: 'Micronesia, Federated States of', shortCode: 'FM' },
  { label: 'Faroe Islands', shortCode: 'FO' },
  { label: 'France', shortCode: 'FR' },
  { label: 'Gabon', shortCode: 'GA' },
  { label: 'United Kingdom', shortCode: 'GB' },
  { label: 'Grenada', shortCode: 'GD' },
  { label: 'Georgia', shortCode: 'GE' },
  { label: 'French Guiana', shortCode: 'GF' },
  { label: 'Guernsey', shortCode: 'GG' },
  { label: 'Ghana', shortCode: 'GH' },
  { label: 'Gibraltar', shortCode: 'GI' },
  { label: 'Greenland', shortCode: 'GL' },
  { label: 'Gambia', shortCode: 'GM' },
  { label: 'Guinea', shortCode: 'GN' },
  { label: 'Guadeloupe', shortCode: 'GP' },
  { label: 'Equatorial Guinea', shortCode: 'GQ' },
  { label: 'Greece', shortCode: 'GR' },
  { label: 'South Georgia and the South Sandwich Islands', shortCode: 'GS' },
  { label: 'Guatemala', shortCode: 'GT' },
  { label: 'Guam', shortCode: 'GU' },
  { label: 'Guinea-Bissau', shortCode: 'GW' },
  { label: 'Guyana', shortCode: 'GY' },
  { label: 'Hong Kong, SAR China', shortCode: 'HK' },
  { label: 'Heard and Mcdonald Islands', shortCode: 'HM' },
  { label: 'Honduras', shortCode: 'HN' },
  { label: 'Croatia', shortCode: 'HR' },
  { label: 'Haiti', shortCode: 'HT' },
  { label: 'Hungary', shortCode: 'HU' },
  { label: 'Indonesia', shortCode: 'ID' },
  { label: 'Ireland', shortCode: 'IE' },
  { label: 'Israel', shortCode: 'IL' },
  { label: 'Isle of Man', shortCode: 'IM' },
  { label: 'India', shortCode: 'IN' },
  { label: 'British Indian Ocean Territory', shortCode: 'IO' },
  { label: 'Iraq', shortCode: 'IQ' },
  { label: 'Iran, Islamic Republic of', shortCode: 'IR' },
  { label: 'Iceland', shortCode: 'IS' },
  { label: 'Italy', shortCode: 'IT' },
  { label: 'Jersey', shortCode: 'JE' },
  { label: 'Jamaica', shortCode: 'JM' },
  { label: 'Jordan', shortCode: 'JO' },
  { label: 'Japan', shortCode: 'JP' },
  { label: 'Kenya', shortCode: 'KE' },
  { label: 'Kyrgyzstan', shortCode: 'KG' },
  { label: 'Cambodia', shortCode: 'KH' },
  { label: 'Kiribati', shortCode: 'KI' },
  { label: 'Comoros', shortCode: 'KM' },
  { label: 'Saint Kitts and Nevis', shortCode: 'KN' },
  { label: 'Korea (North)', shortCode: 'KP' },
  { label: 'Korea (South)', shortCode: 'KR' },
  { label: 'Kuwait', shortCode: 'KW' },
  { label: 'Cayman Islands', shortCode: 'KY' },
  { label: 'Kazakhstan', shortCode: 'KZ' },
  { label: 'Lao PDR', shortCode: 'LA' },
  { label: 'Lebanon', shortCode: 'LB' },
  { label: 'Saint Lucia', shortCode: 'LC' },
  { label: 'Liechtenstein', shortCode: 'LI' },
  { label: 'Sri Lanka', shortCode: 'LK' },
  { label: 'Liberia', shortCode: 'LR' },
  { label: 'Lesotho', shortCode: 'LS' },
  { label: 'Lithuania', shortCode: 'LT' },
  { label: 'Luxembourg', shortCode: 'LU' },
  { label: 'Latvia', shortCode: 'LV' },
  { label: 'Libya', shortCode: 'LY' },
  { label: 'Morocco', shortCode: 'MA' },
  { label: 'Monaco', shortCode: 'MC' },
  { label: 'Moldova', shortCode: 'MD' },
  { label: 'Montenegro', shortCode: 'ME' },
  { label: 'Saint-Martin (French part)', shortCode: 'MF' },
  { label: 'Madagascar', shortCode: 'MG' },
  { label: 'Marshall Islands', shortCode: 'MH' },
  { label: 'Macedonia, Republic of', shortCode: 'MK' },
  { label: 'Mali', shortCode: 'ML' },
  { label: 'Myanmar', shortCode: 'MM' },
  { label: 'Mongolia', shortCode: 'MN' },
  { label: 'Macao, SAR China', shortCode: 'MO' },
  { label: 'Northern Mariana Islands', shortCode: 'MP' },
  { label: 'Martinique', shortCode: 'MQ' },
  { label: 'Mauritania', shortCode: 'MR' },
  { label: 'Montserrat', shortCode: 'MS' },
  { label: 'Malta', shortCode: 'MT' },
  { label: 'Mauritius', shortCode: 'MU' },
  { label: 'Maldives', shortCode: 'MV' },
  { label: 'Malawi', shortCode: 'MW' },
  { label: 'Mexico', shortCode: 'MX' },
  { label: 'Malaysia', shortCode: 'MY' },
  { label: 'Mozambique', shortCode: 'MZ' },
  { label: 'Namibia', shortCode: 'NA' },
  { label: 'New Caledonia', shortCode: 'NC' },
  { label: 'Niger', shortCode: 'NE' },
  { label: 'Norfolk Island', shortCode: 'NF' },
  { label: 'Nigeria', shortCode: 'NG' },
  { label: 'Nicaragua', shortCode: 'NI' },
  { label: 'Netherlands', shortCode: 'NL' },
  { label: 'Norway', shortCode: 'NO' },
  { label: 'Nepal', shortCode: 'NP' },
  { label: 'Nauru', shortCode: 'NR' },
  { label: 'Niue', shortCode: 'NU' },
  { label: 'New Zealand', shortCode: 'NZ' },
  { label: 'Oman', shortCode: 'OM' },
  { label: 'Panama', shortCode: 'PA' },
  { label: 'Peru', shortCode: 'PE' },
  { label: 'French Polynesia', shortCode: 'PF' },
  { label: 'Papua New Guinea', shortCode: 'PG' },
  { label: 'Philippines', shortCode: 'PH' },
  { label: 'Pakistan', shortCode: 'PK' },
  { label: 'Poland', shortCode: 'PL' },
  { label: 'Saint Pierre and Miquelon', shortCode: 'PM' },
  { label: 'Pitcairn', shortCode: 'PN' },
  { label: 'Puerto Rico', shortCode: 'PR' },
  { label: 'Palestinian Territory', shortCode: 'PS' },
  { label: 'Portugal', shortCode: 'PT' },
  { label: 'Palau', shortCode: 'PW' },
  { label: 'Paraguay', shortCode: 'PY' },
  { label: 'Qatar', shortCode: 'QA' },
  { label: 'Réunion', shortCode: 'RE' },
  { label: 'Romania', shortCode: 'RO' },
  { label: 'Serbia', shortCode: 'RS' },
  { label: 'Russian Federation', shortCode: 'RU' },
  { label: 'Rwanda', shortCode: 'RW' },
  { label: 'Saudi Arabia', shortCode: 'SA' },
  { label: 'Solomon Islands', shortCode: 'SB' },
  { label: 'Seychelles', shortCode: 'SC' },
  { label: 'Sudan', shortCode: 'SD' },
  { label: 'Sweden', shortCode: 'SE' },
  { label: 'Singapore', shortCode: 'SG' },
  { label: 'Saint Helena', shortCode: 'SH' },
  { label: 'Slovenia', shortCode: 'SI' },
  { label: 'Svalbard and Jan Mayen Islands', shortCode: 'SJ' },
  { label: 'Slovakia', shortCode: 'SK' },
  { label: 'Sierra Leone', shortCode: 'SL' },
  { label: 'San Marino', shortCode: 'SM' },
  { label: 'Senegal', shortCode: 'SN' },
  { label: 'Somalia', shortCode: 'SO' },
  { label: 'Suriname', shortCode: 'SR' },
  { label: 'South Sudan', shortCode: 'SS' },
  { label: 'Sao Tome and Principe', shortCode: 'ST' },
  { label: 'El Salvador', shortCode: 'SV' },
  { label: 'Syrian Arab Republic (Syria)', shortCode: 'SY' },
  { label: 'Swaziland', shortCode: 'SZ' },
  { label: 'Turks and Caicos Islands', shortCode: 'TC' },
  { label: 'Chad', shortCode: 'TD' },
  { label: 'French Southern Territories', shortCode: 'TF' },
  { label: 'Togo', shortCode: 'TG' },
  { label: 'Thailand', shortCode: 'TH' },
  { label: 'Tajikistan', shortCode: 'TJ' },
  { label: 'Tokelau', shortCode: 'TK' },
  { label: 'Timor-Leste', shortCode: 'TL' },
  { label: 'Turkmenistan', shortCode: 'TM' },
  { label: 'Tunisia', shortCode: 'TN' },
  { label: 'Tonga', shortCode: 'TO' },
  { label: 'Turkey', shortCode: 'TR' },
  { label: 'Trinidad and Tobago', shortCode: 'TT' },
  { label: 'Tuvalu', shortCode: 'TV' },
  { label: 'Taiwan, Republic of China', shortCode: 'TW' },
  { label: 'Tanzania, United Republic of', shortCode: 'TZ' },
  { label: 'Ukraine', shortCode: 'UA' },
  { label: 'Uganda', shortCode: 'UG' },
  { label: 'US Minor Outlying Islands', shortCode: 'UM' },
  { label: 'United States of America', shortCode: 'US' },
  { label: 'Uruguay', shortCode: 'UY' },
  { label: 'Uzbekistan', shortCode: 'UZ' },
  { label: 'Holy See (Vatican City State)', shortCode: 'VA' },
  { label: 'Saint Vincent and Grenadines', shortCode: 'VC' },
  { label: 'Venezuela (Bolivarian Republic)', shortCode: 'VE' },
  { label: 'British Virgin Islands', shortCode: 'VG' },
  { label: 'Virgin Islands, US', shortCode: 'VI' },
  { label: 'Viet Nam', shortCode: 'VN' },
  { label: 'Vanuatu', shortCode: 'VU' },
  { label: 'Wallis and Futuna Islands', shortCode: 'WF' },
  { label: 'Samoa', shortCode: 'WS' },
  { label: 'Yemen', shortCode: 'YE' },
  { label: 'Mayotte', shortCode: 'YT' },
  { label: 'South Africa', shortCode: 'ZA' },
  { label: 'Zambia', shortCode: 'ZM' },
  { label: 'Zimbabwe', shortCode: 'ZW' },
];

export { COUNTRY_CODES };
